
# -----------------------------
# converter-service.yaml
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: converter
  labels:
    app: converter
spec:
  selector:
    app: converter
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP